# Generated by Django 2.2.6 on 2019-11-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='statecode',
        ),
    ]
