# Generated by Django 2.2.6 on 2019-11-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_remove_news_statecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='statecode',
            field=models.CharField(default='DL', max_length=2),
            preserve_default=False,
        ),
    ]
